include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MapAdKillerSettings

MapAdKillerSettings_FILES = MapAdKillerSettingsController.m
MapAdKillerSettings_INSTALL_PATH = /Library/PreferenceBundles
MapAdKillerSettings_FRAMEWORKS = UIKit
MapAdKillerSettings_PRIVATE_FRAMEWORKS = Preferences
MapAdKillerSettings_RESOURCES = Resources/Root.plist
MapAdKillerSettings_CFLAGS = -fobjc-arc -Werror

include $(THEOS_MAKE_PATH)/bundle.mk
